name: Ejecutar Pruebas Automáticas

on:
  push:
    branches:
      - master  # Especifica en qué ramas ejecutar las pruebas. Puedes cambiar "main" por la rama que prefieras.
  pull_request:
    branches:
      - master
#Comentario para probar
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure npm permissions
        run: |
          npm config set user 0
          npm config set unsafe-perm true

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        env:
          NODE_ENV: test  # Asegúrate de que las pruebas se ejecuten en modo de prueba
        run: npm test
